create table film (
id varchar(20) not null,
title varchar(100) not null,
genre varchar(100) not null,
release_year year (10) not null,
cast varchar(200) not null,
synopsis text not null,
image varchar(400) not null,
rating float not null,
carousel VARCHAR(400) default null,
primary key (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

insert into film
values
(101, 'Star Wars', 'Action', '1997', 'Carrie Fisher, Harrison Ford', 'The story of the original trilogy focuses on Luke Skywalkers quest to become a Jedi', 'https://m.media-amazon.com/images/I/81E911hVDAL._AC_SY879_.jpg', 9.2, 'https://phantom-marca.unidadeditorial.es/8e7be6c5cbb3476e86b0196a7be77dba/resize/1320/f/jpg/assets/multimedia/imagenes/2022/05/25/16535003789582.jpg'),
(102, 'Toy Story', 'Animation', '1995', 'Tom Hanks, Tim Allen', 'Toy story is a movie about the secret life of toys where us humans dont know about', 'https://www.ubuy.co.id/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvNjFRUHJxeWRWb0wuX0FDX1NMMTAwMF8uanBn.jpg', 9.5, 'https://movieden.net/wp-content/uploads/2019/06/toy-story-4-7.jpg'),
(103, 'Stranger Things', 'Horror', '2016', 'Millie Bobby Brown, Finn Wolfhard, Noah Schnapp', 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl', 'https://m.media-amazon.com/images/I/8142NLEI3CL._AC_SY741_.jpg', 9.8, 'https://www.dkoding.in/wp-content/uploads/Stranger-Things-Season-4-Release-Date-TV-And-Web-Entertainment-DKODING-2-1.jpg'),
(104, 'How to Train your Dragon', 'Action', '2013', 'Jay Baruchel', 'Hiccup is a Norse teenager from the island of Berk, where fighting dragons are a way of life. His progressive views and weird sense of humor make him a misfit until the dragon toothless came into his life', 'https://mynameismaylia.files.wordpress.com/2014/09/how-to-train-your-dragon-poster-1.jpg', 8.8, 'https://dkfhw9rzsr80z.cloudfront.net/NBC-IN-001-A1187/artworks/posters/NBC-IN-001-A1187-P704.jpg'),
(105, 'IT', 'Horror', '2017', 'Bill Skarsgard', 'Seven young outcasts in Derry, Maine, are about to face their worst nightmare', 'https://cdn.europosters.eu/image/750/posters/it-georgie-i57743.jpg', 9.1, 'https://asset.kompas.com/crops/B17qU88Bl5cuk_6dNi52lttnr9I=/128x85:1152x768/780x390/data/photo/2020/08/24/5f4387221a30a.jpeg'),
(106, 'La La Land', 'Fantasy', '2016', 'Emma Stone, Ryan Gosling', 'Sebastian and Mia  are drawn together by their common desire to do what they love. But as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair', 'https://ae01.alicdn.com/kf/HTB1Va5mQXXXXXcnXXXXq6xXFXXXV/La-La-Land-Film-Cat-Air-inkjet-Fabric-poster-20-X13-07.jpg', 9, 'https://cdn1-production-images-kly.akamaized.net/KFphZ65EYW6PFNFpMyC5LG7jKAk=/640x360/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/1344578/original/053660700_1473770830-emma_sptne.JPG'),
(107, 'Harry Potter', 'Fantasy', '2001', 'Daniel Radcliff, Emma Watson', 'Harry Potter, a boy who learns on his eleventh birthday that he is the orphaned son of two powerful wizards and possesses unique magical powers of his own', 'https://i.pinimg.com/474x/d3/82/b6/d382b6a636bbc08e952ee2316fd1b871.jpg', 9.5, 'https://bookstr.com/wp-content/uploads/2019/07/cropped_MI_main_harry_potter.jpg'),
(108, 'Divergent', 'Action', '2015', 'Theo James, Shailene Woodley', 'Tris Prior lives in world in which society is divided into five factions, she must choose a faction and commit to it for life as she finds out that she fits in all of them', 'https://s3.bukalapak.com/img/3607824896/large/Poster_Film_Divergent.jpg', 9.2, 'https://cdn1-production-images-kly.akamaized.net/egKvZjGiUxg0gBt3oOQCsaiP-x4=/640x360/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/990077/original/6a5bd8e2128feb7d5cbe62825c053552nt-series-insurgent-releasing-date-121.jpg'),
(109, 'Hunger Games', 'Action', '2014', 'Jennifer Lawrence', 'The Capitol of Panem maintains its hold on its 12 districts by forcing them each to select a boy and a girl, called Tributes, to compete in a nationally televised event called the Hunger Games', 'https://m.media-amazon.com/images/I/61Zp7LnSOML._AC_SY679_.jpg', 9.5, 'https://cdn.antaranews.com/cache/800x533/2020/04/22/MV5BNTk4OTg0Mzg4NV5BMl5BanBnXkFtZTcwMDAzODMwNw@@._V1_SX1500_CR0-0-1500-999_AL.jpg'),
(110, 'The Maze Runner', 'Action', '2015', 'Dylan O Brien', 'Thomas, a teenager, arrives in a glade at the center of a giant labyrinth. Like the other youths dumped there before him, he has no memory of his previous life', 'https://s0.bukalapak.com/img/5788579592/large/TheMazeRunner_Poster.jpg', 9, 'https://image.akurat.co/images/uploads/akurat_20170923123215_173KO1.jpg'),

(111, 'Doctor Strange', 'Action', '2016', 'Benedict Cumberbatch', 'Doctor Stephen Strange got into an accident that cost his hands, while on a journey of physical healing,he is drawn into the world of the mystic arts', 'https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_.jpg', 9.5, NULL),
(112, 'Shang-chi', 'Action', '2021', 'Simu Liu', 'Martial-arts master Shang-Chi confronts the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.', 'https://cdn0-production-images-kly.akamaized.net/JiCDYDWDmwp7DDNIBlTTGOzABGE=/640x853/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3434118/original/014340800_1618897521-EzVqwiaVoAIAv-E.jpg', 8.9, 'https://img.tek.id/img/content/2021/11/20/46887/adegan-akhir-shang-chi-emosional-tapi-juga-bermasalah-ini-alasannya-8cSJk5uvvH.jpg'),
(113, 'Hotel Del Luna', 'Fantasy', '2018', 'IU', 'Hotel del Luna is the eponymous hotel that caters only to ghosts, the beautiful but ill-tempered CEO is cursed to manage the hotel due to a terrible crime she committed, but cannot remember', 'https://i.mydramalist.com/RrZozf.jpg', 9, NULL),
(114, 'Kingdom', 'Horror', '2018', 'Ju Jihoon', 'Lee Chang who becomes embroiled in a coup/political conspiracy and is forced to embark upon a mission to investigate the spread of a mysterious undead plague', 'https://0.soompi.io/wp-content/uploads/2020/02/24100516/Kingdom1.jpg', 9.8, NULL),
(115, 'Rise of The Guardians', 'Action', '2012', 'Chris Pine', 'Generation after generation, immortal Guardians like Santa Claus, the Easter Bunny and the Tooth Fairy protects the children with hope until the boogeyman came', 'https://s3.bukalapak.com/img/3936678092/large/Rise_of_the_Guardians_charactercomposter2PPP.jpg', 8.8, NULL),
(116, 'Dune', 'Sci-fi', '2016', 'Zendaya, Timothee Chalamet', 'Paul Atreides, a brilliant gifted young man born into a great destiny, must travel to the most dangerous planet in the universe to ensure the future of his family and his people', 'https://nmsuroundup.com/wp-content/uploads/2022/02/61ux6FzCdGL._AC_SL1280_.jpg', 8.7, NULL),
(117, 'Puss in Boots', 'Action', '2011', 'Antonio Banderas', 'Puss and Humpty reunite to steal a goose that lays golden eggs. Joining them for the adventure of nine lifetimes is notorious cat burglar, Kitty Softpaws', 'https://m.media-amazon.com/images/I/61itgxDIMHL._AC_SY741_.jpg', 8.5, NULL),
(118, 'Goosebumps', 'Fantasy', '2018', 'Jack Black', 'Zach Cooper is surprised to learn that Hannahs mysterious father is R.L. Stine, the famous author of the best-selling "Goosebumps" series. When Zach accidentally unleashes the monsters from the fantastic tales', 'https://s1.bukalapak.com/img/1033164092/large/goosebumps_movie_poster.jpg', 9, NULL),
(119, 'Mean Girls', 'Drama', '2004', 'Lindsay Lohan, Rachel MCadams', 'Cady finally gets to experience public school and gets a quick primer on the cruel, tacit laws of popularity that divide her fellow students into tightly knit cliques', 'https://image.posterlounge.com/images/l/1886777.jpg', 9.8, NULL),
(120, 'Clueless', 'Drama', '1995', 'Alicia Silverstone', 'Shallow, rich and socially successful Cher is at the top of her Beverly Hills high schools pecking scale. Seeing herself as a matchmaker, Cher first coaxes two teachers into dating each other', 'https://m.media-amazon.com/images/I/81QqINwiCGL._AC_SY741_.jpg', 8.8, NULL),

(121, 'Flipped', 'Drama', '2010', 'Callan MCauliffe, Madeline Carroll', 'Juli Baker falls instantly in love with her neighbor, Bryce Loski. Bryce, however, does not feel the spark. Until six year laters, everything flipped', 'https://m.media-amazon.com/images/M/MV5BMTU2NjQ1Nzc4MF5BMl5BanBnXkFtZTcwNTM0NDk1Mw@@._V1_.jpg', 9.9, NULL),
(122, 'The Devil Wears Prada', 'Drama', '2006', 'Anne Hathaway', 'Andy is a recent college graduate with big dreams. Upon landing a job at prestigious Runway magazine, she finds herself the assistant to diabolical editor Miranda Priestly', 'https://m.media-amazon.com/images/M/MV5BZjQ3ZTIzOTItMGNjNC00MWRmLWJlMGEtMjJmMDM5ZDIzZGM3XkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_.jpg', 9, NULL),
(123, 'Space Sweepers', 'Action', '2021', 'Song Joongki, Kim Taeri', 'After snatching a crashed space shuttle in the latest debris chase, Spaceship Victorys crew members find a 7-year-old girl inside. They realise that she is the humanlike robot wanted by UTS Space Guards', 'https://i.pinimg.com/736x/0e/3b/bf/0e3bbfd9cad470960bf5a719859d307a.jpg', 8.6, 'https://mythcreants.com/wp-content/uploads/2021/02/spacesweepers.jpg'),
(124, 'Avatar', 'Action', '2009', 'Zoe Saldana, Sam Worthington', 'On the lush alien world of Pandora live the Navi, beings who appear primitive but are highly evolved. Because the planets environment is poisonous, human/Navi hybrids, called Avatars.', 'https://cdna.artstation.com/p/assets/images/images/031/645/214/large/shreyas-raut-avatar-2.jpg?1604210989', 9.1, NULL),
(125, 'Ready Player One', 'Fantasy', '2018', 'Tye Sheridan, Olivia Cooke', 'In 2045 the planet is on the brink of chaos and collapse, but people find salvation in the OASIS: an expansive virtual reality universe created by eccentric James Halliday', 'https://i.pinimg.com/originals/53/52/dc/5352dc988da504483bc9f23e8730eeb7.jpg', 8.7, NULL),
(126, 'Encanto', 'Drama', '2021', 'Stephanie Beatriz', 'The Madrigals are an extraordinary family that lives in Encanto. The magic of the Encanto has blessed every child in the family with a unique gift every child except Mirabel', 'https://lumiere-a.akamaihd.net/v1/images/encanto-id-poster_b0f0a082.jpeg?region=0%2C0%2C600%2C900', 8.8, 'https://lumiere-a.akamaihd.net/v1/images/g_encanto_1_21512_9af56359.jpeg?region=1,0,1298,730'),
(127, 'High School Musical', 'Drama', '2006', 'Zac Effron, Vanessa Hudgens', 'Troy Bolton the star athlete=, falls for nerdy beauty Gabriella Montez. When they return to campus, Troy and Gabriella audition for the upcoming school musical', 'https://cdn.europosters.eu/image/750/posters/high-school-musical-stage-i3187.jpg', 9.2, NULL),
(128, 'Annie', 'Drama', '2014', 'Quvenzhane Wallis, Jamie Foxx', 'Ever since her parents left her as a baby, little Annie has led a hard knock life However, all that changes when hard-nosed billionaire and mayoral candidate Will Stacks takes her in', 'http://images.fandango.com/images/fandangoblog/ANNIE_DGTL_MKT_TSR_LK2_1.jpg', 8.5, NULL),
(129, 'Mamma Mia!', 'Drama', '2008', 'Amanda Seyfried', 'Donna is preparing for her daughters wedding with the help of two old friends. Meanwhile Sophie, the spirited bride, has a plan', 'https://m.media-amazon.com/images/M/MV5BMTA2MDU0MjM0MzReQTJeQWpwZ15BbWU3MDYwNzgwNzE@._V1_.jpg', 8.2, NULL),
(130, 'Train to Busan', 'Horror', '2016', 'Gongyoo', 'A man, his estranged daughter and other passengers become trapped on a speeding train during a zombie outbreak in South Korea', 'https://m.media-amazon.com/images/M/MV5BMTkwOTQ4OTg0OV5BMl5BanBnXkFtZTgwMzQyOTM0OTE@._V1_FMjpg_UX1000_.jpg', 9.3, NULL),

(131, 'Parasite', 'Horror', '2019', 'Choi Woosik, Park Sodam', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan', 'https://readtimes.id/ptonseeh/2021/01/A1UTpJzoPBL._RI_.jpg', 9.8, 'https://img.jakpost.net/c/2019/06/24/2019_06_24_75017_1561358452._large.jpg'),
(132, 'The Call', 'Horror', '2020', 'Park Shinye', 'Connected by phone in the same home but 20 years apart, a serial killer puts another womans pastand life on the line to change her own fate', 'https://thebannercsi.files.wordpress.com/2021/03/the-call.jpg', 9, 'https://akcdn.detik.net.id/visual/2020/11/02/film-korea-the-call-1_169.jpeg?w=650'),
(133, 'Scream Queens', 'Horror', '2015', 'Emma Roberts, Ariana Grande', 'A semi-anthology series that centers on characters being terrorized by a serial killer in different locations, including a university and a hospital', 'https://m.media-amazon.com/images/M/MV5BYzIwYjkwYTgtNzlhOC00MGZhLWI0OTMtZTAwOTIyNGM4MTJjXkEyXkFqcGdeQXVyMTkzODUwNzk@._V1_FMjpg_UX1000_.jpg', 8, NULL),
(134, 'Inside Out', 'Drama', '2015', 'Amy Poehler, Phyllis Smith', 'Rileys world turns upside-down when she and her parents move to San Francisco. Riley s emotions Joy try to guide her however, the stress of the move brings sadness to the forefront', 'https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_FMjpg_UX1000_.jpg', 9.3, NULL),
(135, 'Sky Castle', 'Drama', '2018', 'Yum Jungah, Kim Hyeyoon, Kim Bora', 'A satirical drama that closely looks at the materialistic desires of upper-class parents in South Korea and how they ruthlessly secure the successes of their families at the cost of destroying others lives', 'https://m.media-amazon.com/images/M/MV5BNTQ1YmFmYmEtZjEwZi00NTI1LWJmMzYtY2NiN2YxMDM5NjJmXkEyXkFqcGdeQXVyMzE4MDkyNTA@._V1_.jpg', 9, NULL),
(136, 'Extraordinary You', 'Fantasy', '2019', 'Kim Hyeyoon, Rowoon', 'The series follows high school girl Eun Danoh who is a student at a prestigious academy. One day, by chance, she discovers that the world she lives in is a fantasy world of comics', 'https://m.media-amazon.com/images/M/MV5BNDc3ODVmZjgtYjIyYy00ZmU5LWJmNjUtYzRhMzM1ZTE5NGNlXkEyXkFqcGdeQXVyNzk0NTA5NQ@@._V1_.jpg', 8.7, 'https://channel-korea.com/wp-content/uploads/2021/04/f1z8ly39tdpf7uegarvj.jpg'),
(137, 'Modern Family', 'Drama', '2009', 'Eric Stonestreet, Sophia Vergara', 'Parents Phil and Claire yearn for an honest, open relationship with their three kids, but a daughter who is trying to grow up too fast, another who is too smart for her own good, and a rambunctious young son make it challenging', 'https://www.themoviedb.org/t/p/original/hamCQmZHbmCJyJrBv7HCBwrizMn.jpg', 8.9, NULL),
(138, 'Friends', 'Drama', '1994', 'Jennifer Anniston, Courteney Cox', 'Six young (20-something) people from New York City (Manhattan), on their own and struggling to survive in the real world', 'https://m.media-amazon.com/images/M/MV5BNDVkYjU0MzctMWRmZi00NTkxLTgwZWEtOWVhYjZlYjllYmU4XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg', 9.2, NULL),
(139, 'Jumanji', 'Action', '2017', 'Jack Black, Dwayne Johnson', 'Four high school kids discover an old video game console and are drawn into the games jungle setting, literally becoming the adult avatars they chose', 'https://images.tokopedia.net/img/cache/700/product-1/2018/1/23/1937770/1937770_50ee66bf-456a-43e5-a83f-a7fe4b123209.jpg', 8.9, NULL),
(140, 'Victorious', 'Musical', '2010', 'Ariana Grande, Victoria Justice', 'The series revolves around aspiring singer Tori Vega, a teenager who attends a performing arts high school called Hollywood Arts High School', 'https://www.ubuy.co.id/productimg/?image=aHR0cHM6Ly9tLm1lZGlhLWFtYXpvbi5jb20vaW1hZ2VzL0kvOTF1aDRnT0JwU0wuX1NMMTUwMF8uanBn.jpg', 8.6, NULL),

(141, 'While You Were Sleeping', 'Fantasy', '2018', 'Suzy, Lee Jongsuk', 'The tale of three young adults who have acquired the ability to see the future through their dreams', 'https://i.pinimg.com/originals/f7/49/7d/f7497d3f48e1dfa593cd9e014211dc0a.jpg', 9, NULL),
(142, 'Moon Lovers', 'Fantasy', '2016', 'IU, Lee Joongi', 'When a total eclipse of the sun took place, a 21st century woman, is transported back in time to the Goryeo Dynasty of Korea, in the body of 16-year-old girl', 'https://m.media-amazon.com/images/M/MV5BNmVmZWRmMjctZDk3OS00MzNlLTllNjAtZmI3YmJhNDRmZTc4XkEyXkFqcGdeQXVyNjgzNjE2MzY@._V1_FMjpg_UX1000_.jpg', 9.1, NULL),
(143, '18 Again', 'Drama', '2020', 'Lee Dohyun', 'The story about a 37 year old man who came back to his 18 year old self to do the things he wasnt able to back then', 'https://i.mydramalist.com/xnNnq_4f.jpg', 8.6, 'https://www.cosmopolitan.co.id/newtest/vrgallery/teaser/yuk-kenalan-sama-5-aktor-muda-tampan-di-k-drama-18-again_64_202010251528476K0MsN.jpg'),
(144, 'All of Us Are Dead', 'Horror', '2022', 'Chan Youngyoon, Park Jihoo', 'he series mostly takes place at a high school in South Korea as a zombie apocalypse suddenly breaks out and threatens the safety of the students', 'https://cdn1-production-images-kly.akamaized.net/wkLzYlPHiXvFPIppqWjjNIC2CT8=/640x853/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3917693/original/022058900_1643359475-all-of-us-are-dead-poster.jpeg', 9.3, 'https://www.small-screen.co.uk/wp-content/uploads/2022/02/all-of-us-are-dead-season-1-netflix.jpg'),
(145, 'The Princess Diaries', 'Drama', '2001', 'Anne Hathaway', 'A clumsy, shy teen discovers that she is the princess of Genovia, a small European state. Thereafter, she must prove to her grandmother that she is worthy of her title', 'https://m.media-amazon.com/images/M/MV5BMzcwYjEwMzEtZTZmMi00ZGFhLWJhZjItMDAzNDVkNjZmM2U5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg', 9.5, NULL),
(146, 'Avengers: End Game', 'Action', '2019', 'Robert Downey JR, Chris Evans, Scarlett Johanson', 'After Thanos, an intergalactic warlord, disintegrates half of the universe, the Avengers must reunite and assemble again to reinvigorate their trounced allies and restore balance', 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg', 9.4, 'https://pbs.twimg.com/media/D40BuNcWAAEVP4r.jpg'),
(147, 'Ada Apa dengan Cinta', 'Romance', '2002', 'Dian Sastro, Nicholas Saputra', 'The romance story between Cinta and Rangga in high school. Cinta is a high school student who is beautiful, accomplished, and surrounded by loyal friends around her', 'https://upload.wikimedia.org/wikipedia/en/d/de/Ada_Apa_dengan_Cinta_film.jpg', 9, NULL),
(148, 'Tenggelamnya Kapal Van der Wijck', 'Romance', '2013', 'Pevita Pearce, Herjunot Ali', 'Zainuddin, a Minang-Mengkasar descent raised by his auntie, decides to go to Padang to deliver his deceased fathers last message about his homeland', 'https://upload.wikimedia.org/wikipedia/id/thumb/2/2b/Poster_film_Tenggelamnya_Kapal_van_der_Wijck.jpg/220px-Poster_film_Tenggelamnya_Kapal_van_der_Wijck.jpg', 8.9, NULL),
(149, 'The Fault in Our Stars', 'Romance', '2015', 'Shailene Woodley, Ansel Elgort', 'Hazel Grace Lancaster (Shailene Woodley), a 16-year-old cancer patient, meets and falls in love with Gus Waters (Ansel Elgort), a similarly afflicted teen from her cancer support group', 'https://m.media-amazon.com/images/M/MV5BNTVkMTFiZWItOTFkOC00YTc3LWFhYzQtZTg3NzAxZjJlNTAyXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg', 9, NULL),
(150, 'Twenty Five Twenty One', 'Romance', '2022', 'Kim Taeri, Nam Joohyuk', 'Na, a once-fencing prodigy, struggles to prove to herself and others that she can reach her full potential after her schools fencing team disbanded due to the 1997 Asian financial crisis', 'https://cdn1-production-images-kly.akamaized.net/abwpJ3zCLR1N--6gIJItJx9-tWw=/640x853/smart/filters:quality(75):strip_icc():format(jpeg)/kly-media-production/medias/3928626/original/011559100_1644396883-kim-tae-ri-nam-joo-hyuk3.jpg', 9.5, 'https://akcdn.detik.net.id/visual/2022/02/08/drama-korea-twenty-five-twenty-one-2022-1_169.webp?w=650');

create table komentar (
id int(11) NOT NULL,
imdb_id varchar(11) NOT NULL,
nama varchar(30) NOT NULL,
komentar text NOT NULL,
tanggal timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
